<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DLL\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FuutaSystemSvcCommonLibrary\FuutaSystemSvcCommonLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="DLL\FuutaSystemSvcVectorLibrary.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="DLL\FuutaSystemSvcVectorLibrary.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
